apiVersion: v1
kind: Service
metadata:
  name: myf
  namespace: myns
  labels:
    app.kubernetes.io/name: myf
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: myf
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000